#!/bin/sh -e
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

DATABASES=$@

## Uncomment the following lines if you want to vacuum the databases after the
## restore. In most cases this is not needed because we are working with
## read-only databases.

# for b in $DATABASES
# do
#   psql -c "VACUUM ANALYZE;" $b
# done

for database in $DATABASES
do
  psql -d template1 -c "ALTER DATABASE $database CONNECTION LIMIT -1;"
done
echo "connections restored"

if [ -x /bin/systemctl ]; then
    sudo /bin/systemctl reload apache2
elif [ -x /etc/init.d/apache2 ]; then
    sudo /etc/init.d/apache2 reload
fi
echo "reload apache"
