#!/bin/sh -e
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

rm /tmp/np

if [ -x /bin/systemctl ]; then
    sudo /bin/systemctl start apache2
elif [ -x /etc/init.d/apache2 ]; then
    sudo /etc/init.d/apache2 start
fi
