#!/bin/sh -e
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR
if [ -f deploy-$PROJECT_NAME.sh ]; then
    # old deploy script
    SVN_CO_OPTIONS="--username readonly --password readonly"
    sh deploy-$PROJECT_NAME.sh -r -c $PROJECT_NAME/configs/$TARGET
elif [ -f buildout_$TARGET.cfg ]; then
    # buildout with a specific config file
    buildout/bin/buildout -c buildout_$TARGET.cfg
elif [ -f buildout_main.cfg ]; then
    # buildout with a generic config file
    buildout/bin/buildout -c buildout_main.cfg
elif [ -f buildout.cfg ]; then
    # buildout without a generic config file
    buildout/bin/buildout -c buildout.cfg
fi
