#!/bin/sh -e
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

DATABASES=$@

for database in $DATABASES
do
  psql -d template1 -c "ALTER DATABASE $database CONNECTION LIMIT 0;"
  psql -d $database -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid();"
done
echo "connections locked and cleared"
