#!/bin/sh -e
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

DATABASES=$@

# apache must be stopped to prevent database connection during
# databases / tables restore.
if [ -x /bin/systemctl ]; then
    sudo /bin/systemctl stop apache2
elif [ -x /etc/init.d/apache2 ]; then
    sudo /etc/init.d/apache2 stop
fi
