#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR/cartoweb3/htdocs/
rm -f index.html
ln -fs client.php index.php

exit 0
