#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#   $CW_PROJECT: the cartoweb3 project name (cw_project in env section)
#

PROJECT_NAME=$1
CODE_DIR=$2

CONF=$CODE_DIR/cartoweb3/projects/$CW_PROJECT/deployment/config_$TARGET.properties

cd $CODE_DIR/cartoweb3/
if [ -f $CONF ]; then
    php cw3setup.php --install --project $CW_PROJECT --default-project $CW_PROJECT --config-from-file $CONF
else
    php cw3setup.php --install --project $CW_PROJECT --default-project $CW_PROJECT --config-from-project $CW_PROJECT
fi

cd $CODE_DIR/cartoweb3/htdocs/
rm -f index.html
ln -fs client.php index.php

exit 0
