#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

DATABASES=$@

if [ -x /bin/systemctl ]; then
    sudo /bin/systemctl start apache2
elif [ -x /etc/init.d/apache2 ]
    sudo /etc/init.d/apache2 start
fi

exit 0
