#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

DATABASES=$@

if [ -x /etc/init.d/apache2 ]; then
    sudo /etc/init.d/apache2 stop
fi

if [ -x /etc/init.d/postgresql ]; then
    sudo /etc/init.d/postgresql restart
fi

exit 0
