#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

DATABASES=$@

for b in $DATABASES
do
  psql -c "VACUUM ANALYZE;" $b
done

exit 0
