#!/bin/sh
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

if [ -x /usr/sbin/apache2ctl ]; then
    sudo /usr/sbin/apache2ctl graceful
fi

exit 0
